apiVersion: apps/v1
kind: Deployment
metadata:
  name: webssh-prod
spec:
  selector:
    matchLabels:
      app: webssh
  template:
    metadata:
      labels:
        app: webssh
    spec:
      containers:
      - name: webssh
        image: ghcr.io/dbca-wa/webssh:1.6.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        startupProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /tmp
            name: tmpfs-ram
      volumes:
        - name: tmpfs-ram
          emptyDir:
            medium: "Memory"
---
apiVersion: v1
kind: Service
metadata:
  name: webssh-clusterip-prod
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
  selector:
    app: webssh
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webssh-ingress-prod
spec:
  rules:
    - host: webssh.dbca.wa.gov.au
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: webssh-clusterip-prod
              port:
                number: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webssh-hpa-prod
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webssh-prod
  metrics:
    - resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 250
      type: Resource
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webssh-pdb-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: webssh
