apiVersion: apps/v1
kind: Deployment
metadata:
  name: webssh-uat
spec:
  selector:
    matchLabels:
      app: webssh
  template:
    metadata:
      labels:
        app: webssh
    spec:
      containers:
        - name: webssh-uat
          image: ghcr.io/dbca-wa/webssh:1.6.3@sha256:8c4e752b8630e7555b6a959f9cd2b588985a24b5c826fcbe673dce677ada9fc1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: '64Mi'
              cpu: '5m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs-ram
      volumes:
        - name: tmpfs-ram
          emptyDir:
            medium: 'Memory'
      automountServiceAccountToken: false
      tolerations:
        - key: arch
          operator: Equal
          value: arm64
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: arch
                    operator: In
                    values:
                      - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: webssh
                topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: webssh-clusterip-uat
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
  selector:
    app: webssh
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webssh-ingress-uat
spec:
  rules:
    - host: webssh-uat.dbca.wa.gov.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webssh-clusterip-uat
                port:
                  number: 8080
